### ISSUE TITLE
Busy is not red

### ISSUE THREAD

**Issue by Eisbaeeer** [toblum/ESPTeamsPresence#12]
Now I get running it with the pre-compiled version. But when I compile by my own, it will not authenticate.
First question:
I saw that "DISABLECERTCHECK 1"  in config of new version. Is this enabled in actual pre-compiled version?
How can I change the color of busy? My stripe lights purple instead of red.
Thank you verry much!
This project is realy awesome!

**Comment by Eisbaeeer** [comment]
Mea culpa. Seen, that busy is right with the colour purple. In a call will be red. So I will close the issue. Sorry for that. The presence working verry well! Great!

**Comment by toblum** [comment]
Great, good to hear!

Greetings!
