### ISSUE TITLE
Falshed my DOIT ESP32 | flash read err, 1000

### ISSUE THREAD

**Issue by Jimbobnz** [toblum/ESPTeamsPresence#20]
Flash my ESP32 using the NODEMCU PYFlasher

Serial Monitor Responce:

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
Falling back to built-in command interpreter.
OK

-------------------

Command: esptool.py --port COM5 --baud 460800 --after no_reset write_flash --flash_size detect --flash_mode dio 0x00000 C:\Users\James\Downloads\firmware.bin

esptool.py v3.0
Serial port COM5
Connecting........_
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6 (revision 0)
Features: WiFi, BT, Dual Core, Coding Scheme None
Crystal is 40MHz
MAC: 30:ae:a4:02:ed:6c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 1084256 bytes to 629464...
Wrote 1084256 bytes (629464 compressed) at 0x00000000 in 16.2 seconds (effective 536.3 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.

Firmware successfully flashed. Unplug/replug or reset device 
to switch back to normal boot mode.

**Comment by toblum** [comment]
Hi @Jimbobnz,

a bit more context would be helpful.

From the messages it looks like a problem with the ESP32 bootloader and not related with the firmware.
This could have many causes and could be hardware related (faulty memory), power related (unstable power supply) or error when flashing the firmware. Or a combination. I didn't experience this before.

Most likely the bootloader was overwritten on a flashing attempt. You might want to try this tool, to restore the bootloader and partitions: https://github.com/neoxharsh/ESP32-GUI-Flasher (bootloader.bin to flash is also in the GitHub there) and bring the ESP32 back to life. Then flashing the ESPTeamsPresence again.

Greetings
