### ISSUE TITLE
Is there a way to change the color order?

### ISSUE THREAD

**Issue by patdelaney** [toblum/ESPTeamsPresence#21]
If I use a neopixel ring the colors are correct. If I use 5v ws2811 12mm bullet nodes the colors are off. The bullets are RGB color order.

**Comment by toblum** [comment]
Hi @patdelaney,

this is something that can be changed only in code: https://github.com/toblum/ESPTeamsPresence/blob/41d1980819130d8e429647f2bddb53c438c5e422/src/main.cpp#L133

Possible values are:
//   NEO_KHZ800  800 KHz bitstream (most NeoPixel products w/WS2812 LEDs)
//   NEO_KHZ400  400 KHz (classic 'v1' (not v2) FLORA pixels, WS2811 drivers)
//   NEO_GRB     Pixels are wired for GRB bitstream (most NeoPixel products)
//   NEO_RGB     Pixels are wired for RGB bitstream (v1 FLORA pixels, not v2)
//   NEO_RGBW    Pixels are wired for RGBW bitstream (NeoPixel RGBW products)

Greetings
