### ISSUE TITLE
Generic Client-ID not working

### ISSUE THREAD

**Issue by Eisbaeeer** [toblum/ESPTeamsPresence#22]
Hi. It seems, that the generic Client-ID not working anymore. I don´t get the code with the generic-ID. If I use a code from our  Azure, it works great.

**Comment by toblum** [comment]
Hi @Eisbaeeer,

I can't see any problems at the moment. I'm using it on my own devive and could relogin.
What error did you get? Maybe there are now restrictions on your tenant in place for your user.

Greetings
Tobias

**Comment by Eisbaeeer** [comment]
Let me check that with my private account. I will give you a reply.

**Comment by Eisbaeeer** [comment]
It works but blocked by our Azure.
