### ISSUE TITLE
No status updates anymore

### ISSUE THREAD

**Issue by schmitzmichael** [toblum/ESPTeamsPresence#30]
Hello Tobias,

since a couple of days, my TeamsPresenceLight isn´t working anymore.
I started the device login a  couple of times, but no change.

I have also flashed the ESP again and did a complete new configuration.
Is the generic Client ID still usable?
Or is it possible, that our IT change something in the Azure Backend?

In the console i can see "Waiting for authorization by user: ......: OAuth 2.0 device flow error. Authorization is pending. Continue polling.

By the way, are you still planning to update your firmware with additional features?
- Show presence status on device website
- change the light manually
- etc.

Best regards
Michael

**Comment by schmitzmichael** [comment]
after a refresh I now get the info, that Auth token is valid.

But the error is now: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed.

Any suggestions?

**Comment by schmitzmichael** [comment]
one additional update. I created a new App registration in the tenant and changed the ClientID in my BusyLight config. When I now want to start the device login, I get this error in the console: The request body must contain the following parameters: 'client_assertion' or 'client_secret'.

I have the client_secret, but there is no option to add this to the configuration, right? Or do i have to delete the security part from my enterprise app?

**Comment by toblum** [comment]
Hi @schmitzmichael,

please have a look at https://github.com/toblum/ESPTeamsPresence/issues/29. There were changes to the SSL certificates used by Microsoft. I have now released [v.0.18.3](https://github.com/toblum/ESPTeamsPresence/releases/tag/v0.18.3) which should fix the problems.

Many greetings
Tobias

**Comment by toblum** [comment]
Regarding the app registration:


### When you create your own app registration, you should make the following settings:
![image](https://user-images.githubusercontent.com/18660238/226181811-d5ac955c-2db7-481e-95df-f6799eb0d1d7.png)


### Add "Mobile and desktop applications" as platform with "nativeclient" redirect URI:
![image](https://user-images.githubusercontent.com/18660238/226181416-0044a8b1-1113-44f0-b13b-8f31f4af07c5.png)

### That should automatically allow public client flows:
![image](https://user-images.githubusercontent.com/18660238/226181495-7937c07c-56dc-402e-9d4c-b9f8c4b1e142.png)

### And you should add the following delegated permissions and give admin consent:
![image](https://user-images.githubusercontent.com/18660238/226182079-dced1731-faf0-4d4a-9835-0de1b8e038b5.png)
