### ISSUE TITLE
[Not Issue]Azure Application registration manifest

### ISSUE THREAD

**Issue by pish181** [toblum/ESPTeamsPresence#31]
Hi,

Could you please share application registration manifest from Azure Active Directory so it can be used to create similar configuration to be used in personal tenant?

Thank you.

**Comment by toblum** [comment]
@pish181 Have a look here: https://github.com/toblum/ESPTeamsPresence/issues/30#issuecomment-1475274011
There you'll find the relevant settings

**Comment by pish181** [comment]
thank you very much.
