### ISSUE TITLE
No device Login code

### ISSUE THREAD

**Issue by NKaaay** [toblum/ESPTeamsPresence#35]
Hey Tobias,

i want to build also a Teams Presence Light like yours but the firmware did not give me a Login code.
I hope you could help me there.
Here a screenshot:
![2023-08-16 07_33_47-Window](https://github.com/toblum/ESPTeamsPresence/assets/113265583/59596954-5949-4781-af6c-35d70af45402)
testet with firmware 0.18.1 & 0.18.3

Best regards
Niclas

**Comment by toblum** [comment]
Hi @NKaaay,

that could be a wrong ClientID and/or tenant name. You should double-check these both values, also for leading/trailing spaces.
If these are correct then a look at the serial console of the ESP might help. And errors shown there?

Greetings!

**Comment by NKaaay** [comment]
Ok Thanks. I have solved this problem with my Tenant GUID instead of the eMail-Adress.
But now i have an other problem. I have no admin rights in the organization and can not complete the last step...

**Comment by toblum** [comment]
OK, good to know that it works in general. But you'll need someone with appropriate rights to approve that last step if it's restricted in your organization. No way around that.
