### ISSUE TITLE
´WiFi Password

### ISSUE THREAD

**Issue by HoLHey** [toblum/ESPTeamsPresence#39]
I have a problem with the latest firmware. My WLAN password has 38 digits. I cannot enter these via the web interface.

**Comment by toblum** [comment]
Hi @HoLHey,

this seems to be an limitation in the IotWebConf library used in this project. Not sure if this can be changed easily.
Do you maybe have a guest wifi option in your network or a separate (phone?) hotspot that you can use?

Greetings
