### ISSUE TITLE
Asking for username / password when changing configuration?

### ISSUE THREAD

**Issue by SethColeman** [toblum/ESPTeamsPresence#7]
When trying to modify the configuration via browser (connected to my home wifi), I get a username / password login popup box.

Serial monitor shows: 
![image](https://user-images.githubusercontent.com/25418158/99094418-c7624280-25a1-11eb-9e96-4fe395edf262.png)

**Comment by toblum** [comment]
Hi @SethColeman,

I need to write that down better. To update configuration you need to login with user "admin" and the password you provided during setup. (Default is "presence")

Hope that works

Greetings

**Comment by SethColeman** [comment]
Toblum, Ok, I'll try it out next time I have the issue. I was able to reset the device to defaults and get it to work. When I was having the issue I had an incorrect tenant ID and I was unable to get back in to fix it. I'm just waiting on my IT department to (hopefully) approve my azure request...

**Comment by toblum** [comment]
OK, great, feel free to ask, if you have any issues!
